name: Deploy Complex Project
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t moemoo5588/react-test -f Dockerfile.dev ./multi-client
      - run: docker run -e CI=true moemoo5588/react-test npm test
      - run: docker build -t moemoo5588/client ./multi-client
      - run: docker build -t moemoo5588/nginx ./nginx
      - run: docker build -t moemoo5588/server ./server
      - run: docker build -t moemoo5588/worker ./worker
      - run: docker push moemoo5588/client
      - run: docker push moemoo5588/nginx
      - run: docker push moemoo5588/server
      - run: docker push moemoo5588/worker
 
#       - name: Generate deployment package
#         run: zip -r deploy.zip . -x '*.git*'
 
#       - name: Deploy to EB
#         uses: einaregilsson/beanstalk-deploy@v18
#         with:
#           aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
#           aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
#           application_name: react
#           environment_name: React-env
#           existing_bucket_name: elasticbeanstalk-ap-south-1-739643389553
#           region: ap-south-1
#           version_label: ${{ github.sha }}
#           deployment_package: deploy.zip